name: Build and Test

on:
  pull_request:
    types: [ opened, reopened, synchronize, review_requested ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install dependencies
        run: cd backend && go mod tidy

      - name: Run tests
        run: cd backend && go test ./...

      - name: Build application
        run: cd backend && go build -o app

  delete-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Delete branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}
          force: true
